title: Mein Blog
email: info@example.com
description: >- 
  Ein einfacher Jekyll-Blog mit Homepage, Blog, Impressum und Datenschutz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
